# -*- coding: utf-8 -*-
"""03-Python_ejercicios_clases.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NN5-voAQTFnYK0KVkjwHKB8MJlKlv2uM

---
# Objetos

Define la clase Baraja.
Define el constructor de manera que le tengas que pasar una lista de "palos" y una lista de "números".

Define la función "shuffle" y "draw".
"""

import random

#Baraja de texto
class Baraja:
  def __init__(self, numeros, palos):
      self.numeros = numeros
      self.palos = palos
      self.cartas = []

      for palo in self.palos:
          for numero in self.numeros:
              carta_nueva = f"{numero} de {palo}"
              self.cartas.append(carta_nueva)

  def shuffle(self):
      print("Barajar el mazo")
      random.shuffle(self.cartas)

  def draw(self):
      if len(self.cartas) > 0:
          return self.cartas.pop()
      else:
          return "No quedan cartas"
#Prueba
mazo1 = Baraja(["A","2","3","4","5","6","7","8","9","J","Q","K"], ["Oros", "Copas", "Picas", "Corazones"])
mazo1.shuffle()
print(f"Robo una carta: {mazo1.draw()}")



"""Inicializa una baraja de poker, roba 5 cartas y muestralas por pantalla."""

#Elementos del poker: numeros y palos
palos_poker = ["Picas", "Corazones", "Tréboles", "Diamantes"]
numeros_poker = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"]

#Inicializamos (instanciar)
mazo_poker = Baraja(palos_poker, numeros_poker)
print(f"Baraja creada con {len(mazo_poker.cartas)} cartas")

#Barajar el mazo
mazo_poker.shuffle()

#Robar las 5 cartas y las imprimimos en pantalla
print("\n Mis cinco cartas")

mano_poker = []
for i in range(5):
    carta = mazo_poker.draw()
    mano_poker.append(carta)
    print(f"Carta {i+1}: {carta}")

print(f"\nQuedan {len(mazo_poker.cartas)} cartas en el mazo.")

"""Crees que vale la pena crear el objeto "carta"?

Crea la clase carta y reescribe la clase baraja.

Crea la clase "hand" con la función "discard", que en el caso del poker significa tirar todas las cartas.
"""

class Carta:
  def __init__(self, numero, palo):
      self.numero = numero
      self.palo = palo

  def __repr__(self):
      return f"{self.numero} de {self.palo}"

  #Mejoras de la clase barajas
class Baraja:
  def __init__(self, numeros, palos):
      self.cartas = []
      for palo in palos:
          for numero in numeros:
              self.cartas.append(Carta(numero, palo))

  def shuffle(self):
      print("Barajando las cartas")
      random.shuffle(self.cartas)

  def draw(self):
      if len(self.cartas) > 0:
          return self.cartas.pop()

      else:
        return "No quedan cartas"


class Hand:
  def __init__(self):
    self.cartas = [] #inicializamos con la mano vacía

#REcibimos cartas
  def add_card(self, carta):
    self.cartas.append(carta)

#descartamos cartas
  def discard(self):
    self.cartas.clear()

    print("Descartamos todas las cartas")

#Comprobación
#creamos la mano del jugador
mano_jugador1 = Hand()

#Damos una mano simulada
mano_jugador1.add_card("As de picas")
mano_jugador1.add_card("10 de Corazones")

print(f"Cartas en mano antes de descartar: {mano_jugador1.cartas}")

#Descartamos
mano_jugador1.discard()

print(f"Cartas en mano después de descartar: {mano_jugador1.cartas}")



  # Comprobación del código
numeros = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"]
palos = ["♥️", "♦️", "♣️", "♠️"]

mazo = Baraja(numeros, palos)
mazo.shuffle()

carta = mazo.draw()

print(f"He robado un: {carta}")
print(f"El palo es {carta.palo} y el número es {carta.numero}")

"""Inicializa una baraja de "hanabi" y manos para 4 jugadores.

Que modificarias de la clase "hand" para poder implementar el descarte del hanabi (descartar una carta y robar otra)?

Hanabi:
    5 cartas por jugador
    5 palos (blanco, verde, rojo, amarillo y azul)
    10 números por palo (3 unos, 2 doses, 2 treses, 2 cuatros, 1 cinco)

"""

import random


class Carta:
  def __init__(self, numero, palo):
      self.numero = numero
      self.palo = palo

  def __repr__(self):
      return f"{self.numero} de {self.palo}"

  #Mejoras de la clase barajas
class Baraja:
  def __init__(self, numeros, palos):
      self.cartas = []
      for palo in palos:
          for numero in numeros:
              self.cartas.append(Carta(numero, palo))

  def shuffle(self):
      print("Barajando las cartas")
      random.shuffle(self.cartas)

  def draw(self):
      if len(self.cartas) > 0:
          return self.cartas.pop()

      else:
        return "No quedan cartas"


class HandHanabi:
  def __init__(self, nombre):
      self.nombre = nombre
      self.cartas = [] #inicializamos con la mano vacía

#REcibimos cartas
  def add_card(self, carta):
      self.cartas.append(carta)

#descartamos cartas
  def discard_card(self, posicion):
    #verificamos que la posición sea válida (que no se pase del rango)
      if 0 <= posicion < len(self.cartas):
          carta_tirada = self.cartas.pop(posicion)
          print(f"{self.nombre} ha descartado: {carta_tirada}")
          return carta_tirada
      else:
          print("Error: {self.nombre} esa posición no existe en tu mano")
          return None

#Main (Juego)

#Estructura del juego
#palos por colores
colores_hanabi = ["Blanco", "Verde", "Rojo", "Amarillo", "Azul"]

#numeros
numeros_hanabi = [1,1,1,2,2,3,3,4,4,5]

#creamos la baraja
mazo_hanabi = Baraja(colores_hanabi, numeros_hanabi)
print(f"Baraja Hanabi creado con {len(mazo_hanabi.cartas)} cartas")
#Barajamos con shuffle
mazo_hanabi.shuffle()

#Creamos los 4 jugadores (manos c/u)
jugador1 = HandHanabi("Jugador 1")
jugador2 = HandHanabi("Jugador 2")
jugador3 = HandHanabi("Jugador 3")
jugador4 = HandHanabi("Jugador 4")

#lista de jugadores
todos_los_jugadores = [jugador1, jugador2, jugador3, jugador4]

#Repartición de las 5 cartas iniciales
print("\n Repartiendo 🃏 ")
for jugador in todos_los_jugadores:
  for _ in range(5):
      jugador.add_card(mazo_hanabi.draw())
  print(f"Mano incial de {jugador.nombre}: {jugador.cartas}")

#Descartamos por turnos
print("\n Turnos de descarte de los jugadores")
jugador1.discard_card(3) #posición 3, 4ta carta
jugador2.discard_card(1) #posición 2, 3era carta
jugador3.discard_card(4) #posición 4, 5ta carta
jugador4.discard_card(2) #posición 2, 3era carta


#robamos para reponer
print("\n Reponemos manos")

for jugador in todos_los_jugadores:
  nueva_carta = mazo_hanabi.draw()
  jugador.add_card(nueva_carta)
  print(f"{jugador.nombre} ha robado: {nueva_carta}")

print("\n--- 🏁 MANOS FINALES ---")
print(f"Mano final: {jugador1.cartas}")
print(f"Mano final: {jugador2.cartas}")
print(f"Mano final: {jugador3.cartas}")
print(f"Mano final: {jugador4.cartas}")